#!/bin/bash

set -e -o pipefail

echo "Starting bootstrap!"

# Create some folders
echo "Creating some useful folders..."
mkdir -p ~/.fonts
mkdir -p ~/.gnupg
mkdir -p ~/.lein
mkdir -p ~/.tmp
mkdir -p ~/.ssh
mkdir -p ~/code

echo "Installing packages..."
./install

echo "Creating dotfiles links in ~..."
./make-links

# Setup mta
echo "Setting up SMTP MTA..."
echo "root: fabrizio@ferrai.io" >> /etc/aliases && newaliases

# Decrypt stuff
echo "Decrypting all the things..."
gpg2 --no-tty -q -d ~/mail/msmtp-password.gpg > ~/.tmp/mailpass
gpg2 --no-tty -q -d ~/dotfiles/cryptd/pushbullet-token.gpg > ~/.tmp/pb-token
gpg2 --no-tty -q -d ~/dotfiles/cryptd/idea15.jar.gpg > ~/.tmp/idea15.jar
./bin/decrypt-fonts

# Setup SSH repo
echo "Switching the repo over to SSH..."
git remote set-url origin git@github.com:ff-/dotfiles.git

echo "Done!"
