#!/bin/bash

set -e -o pipefail

echo "Starting bootstrap!"

# Create some folders
echo "Creating some useful folders..."
mkdir -p ~/.gnupg
mkdir -p ~/.tmp
mkdir -p ~/.ssh
mkdir -p ~/code

echo "Installing packages..."
./install

echo "Creating dotfiles links in ~..."
./make-links

# Setup mta
echo "Setting up SMTP MTA..."
gpg2 --no-tty -q -d ~/mail/msmtp-password.gpg > ~/.tmp/mailpass
echo "root: fabrizio@ferrai.io" >> /etc/aliases && newaliases

# Decrypt Pushbullet token
echo "Decrypting Pushbullet token..."
gpg2 --no-tty -q -d ~/dotfiles/cryptd/pushbullet-token.gpg > ~/.tmp/pb-token

# Setup SSH repo
echo "Switching the repo over to SSH..."
git remote set-url origin git@github.com:ff-/dotfiles.git

echo "Done!"
