#!/bin/bash

# Docker
sudo apt update
sudo apt install -y apt-transport-https ca-certificates linux-image-extra-$(uname -r) linux-image-extra-virtual
sudo apt-key adv --keyserver hkp://p80.pool.sks-keyservers.net:80 --recv-keys 58118E89F3A912897C070ADBF76221572C52609D
echo "https://apt.dockerproject.org/repo ubuntu-xenial main" | sudo tee /etc/apt/sources.list.d/docker.list

# Atom
sudo add-apt-repository -y ppa:webupd8team/atom

# Install everything
sudo apt update
sudo apt install -y msmtp msmtp-mta gnupg2 rlwrap curl wget xdotool javascriptcoregtk-4.0 libzip4 atom zsh git autojump docker-engine default-jdk
sudo apt upgrade -y

# Curl installs
## $1: name, $2: url
curl-install () {
  sudo bash -c "cd /usr/local/bin && curl -fsSLo $1 $2 && chmod 755 $1"
}

## Leiningen
curl-install lein https://raw.githubusercontent.com/technomancy/leiningen/stable/bin/lein
lein

## Boot
curl-install boot https://github.com/boot-clj/boot-bin/releases/download/latest/boot.sh
boot

## Planck
curl-install planck http://planck-repl.org/releases/2.0-alpha5-ubuntu-16.04/planck

## Prezto
git clone https://github.com/sorin-ionescu/prezto.git -o ~/.zprezto

# Atom packages
apm install --packages-file ~/dotfiles/atom/packages.list

# TODO android studio
# TODO pip install pushbullet
