#!/bin/bash

set -e -o pipefail

# Brew installs
## Taps
brew tap caskroom/versions
brew tap d12frosted/emacs-plus
brew tap caskroom/fonts
brew update

## Emacs
brew install emacs-plus
brew linkapps emacs-plus

## Command-line software
brew install wget htop trash ag coreutils zsh rlwrap httpie python node autojump gnupg2

# Cask installs
## Dev stuff
brew cask install java iterm2 sourcetree dash

## Editors
brew cask install atom lighttable

## Messaging
brew cask install telegram slack

## Media
brew cask install spotify spotify-notifications vlc

## Virtualization
brew cask install virtualbox docker vagrant

## System utils
brew cask install flux caffeine alfred bettertouchtool the-unarchiver

## Misc 
brew cask install little-snitch dropbox obs unity appcleaner firefox google-chrome

## Fonts
brew cask install font-source-code-pro font-fira-code

# Python
pip install --upgrade pip setuptools
pip3 install --upgrade pip setuptools wheel

# Clojure
brew install leiningen
brew install boot-clj
boot
boot # calling two times to complete all the upgrades
brew install lumo


# Prezto
git clone --recursive https://github.com/sorin-ionescu/prezto.git "${ZDOTDIR:-$HOME}/.zprezto"


# Spacemacs
git clone https://github.com/syl20bnr/spacemacs ~/.emacs.d
